sudo: required
language: node_js
services:
  - docker

node_js:
  - v14
  - v13
  - v12
  - v10

cache:
  directories:
    - ~/.npm
    - ~/.cache

  override:
    - npm ci

before_install:
  - docker version
  - docker-compose version

script:
  - npm run docker
  - docker ps -a
  - sleep 5
  - npm run test

jobs:
  include:
  - stage: npm Deployment
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
